name: publish

on: [push]

jobs:
  publish-image:
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/k0ka/rhel-php-fpm:latest
          build-args: PHP_VERSION=${{ matrix.php }}