name: publish

on: [push]

jobs:
  publish-image:
    strategy:
      matrix:
        php: ['7.4']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build --build-arg PHP_VERSION --tag ghcr.io/k0ka/rhel-php-fpm:latest .
          docker push ghcr.io/k0ka/rhel-php-fpm:latest
        with:
          PHP_VERSION: ${{ matrix.php }}